[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
rustflags = [
    "-C", "default-linker-libraries=no",
    "-C", "target-cpu=cortex-m4",
    "-C", "target-feature=-fpregs",
]

[profile.release]
debug = true
